---

mysql_datadir: /var/lib/mysql
mysql_socket: /var/lib/mysql/mysql.sock
mysql_port: 3306
mysql_log_bin: /var/lib/mysql/mysql_binary_log
mysql_log: /var/log/mariadb/mariadb.log
mysql_pid_dir: /var/run/mariadb
mysql_pid_file: "{{ mysql_pid_dir }}/mariadb.pid"
mysql_innodb_log_buffer_size: 64M
mysql_innodb_buffer_pool_size: 4G
mysql_root_password: changeme

# Supported database types: mysql,postgresql,...
database_type: mysql

databases:
  scm:
    name: 'scm'
    user: 'scm'
    pass: 'scm_password'
    type: '{{ database_type }}'
  amon:
    name: 'amon'
    user: 'amon'
    pass: 'amon_password'
    type: '{{ database_type }}'
  rman:
    name: 'rman'
    user: 'rman'
    pass: 'rman_password'
    type: '{{ database_type }}'
  nav:
    name: 'nav'
    user: 'nav'
    pass: 'nav_password'
    type: '{{ database_type }}'
  navms:
    name: 'navms'
    user: 'navms'
    pass: 'navms_password'
    type: '{{ database_type }}'
  metastore:
    name: 'metastore'
    user: 'hive'
    pass: 'hive_password'
    type: '{{ database_type }}'
  sentry:
    name: 'sentry'
    user: 'sentry'
    pass: 'sentry_password'
    type: '{{ database_type }}'
  hue:
    name: 'hue'
    user: 'hue'
    pass: 'hue_password'
    type: '{{ database_type }}'
  oozie:
    name: 'oozie'
    user: 'oozie'
    pass: 'oozie_password'
    type: '{{ database_type }}'
  das:
    name: 'das'
    user: 'das'
    pass: 'das_password'
    type: '{{ database_type }}'
  ranger:
    name: 'ranger'
    user: 'ranger'
    pass: 'ranger_password'
    type: '{{ database_type }}'
